[package]
name = "workspaces"
version = "0.2.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
oxibar-plugin-api = { path = "../../crates/oxibar-plugin-api" }
iced = { version = "0.14.0", features = [
	"advanced",
	"canvas",
	"image",
	"svg",
	"tokio",
]}
oxiced = { git = "https://github.com/Xetibo/oxiced", branch = "iced14" }
hyprland = "0.4.0-beta.3"
iced_anim = "0.3.1"
tracing = "0.1"
