[package]
name = "notifications"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
oxibar-plugin-api = { path = "../../crates/oxibar-plugin-api" }
iced = { version = "0.14.0", features = [
	"advanced",
	"tokio",
]}
oxiced = { git = "https://github.com/Xetibo/oxiced", branch = "iced14" }
zbus = { version = "5.14.0", features = ["blocking"] }
