[package]
name = "tray"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
oxibar-plugin-api = { path = "../../crates/oxibar-plugin-api" }
iced = { version = "0.14.0", features = [
	"advanced",
	"image",
	"svg",
	"tokio",
]}
oxiced = { git = "https://github.com/Xetibo/oxiced", branch = "iced14" }
serde = "1.0"
tracing = "0.1"
zbus = "5.14.0"
